spring:
  application:    name: servicio-usuarios
server:
  port: ${PORT:0}
eureka:
  client:
    service-url:      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} 
    
# Muestra en consola las consulatas o sentencias que se realizen con el JPA.
logging:  level:    org:
      hibernate:
        SQL: debug